CREATE TABLE `job_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobId` int NOT NULL,
	`userId` int NOT NULL,
	`applicantName` varchar(255) NOT NULL,
	`applicantEmail` varchar(320) NOT NULL,
	`resumeUrl` varchar(500),
	`coverLetter` text,
	`certifications` text,
	`yearsExperience` int,
	`status` enum('submitted','reviewing','shortlisted','rejected','accepted') NOT NULL DEFAULT 'submitted',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `job_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `job_postings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`company` varchar(255) NOT NULL,
	`location` varchar(255) NOT NULL,
	`locationType` enum('remote','hybrid','onsite') NOT NULL DEFAULT 'remote',
	`country` varchar(100),
	`payRate` int NOT NULL,
	`payRateMax` int,
	`payCurrency` varchar(3) NOT NULL DEFAULT 'USD',
	`experienceLevel` enum('entry','mid','senior','lead') NOT NULL DEFAULT 'entry',
	`employmentType` enum('full_time','part_time','contract','freelance') NOT NULL DEFAULT 'full_time',
	`description` text NOT NULL,
	`responsibilities` text,
	`requirements` text,
	`requiredCertifications` text,
	`preferredCertifications` text,
	`benefits` text,
	`applicationUrl` varchar(500),
	`contactEmail` varchar(320),
	`status` enum('active','closed','draft') NOT NULL DEFAULT 'active',
	`postedBy` int,
	`viewCount` int NOT NULL DEFAULT 0,
	`applicationCount` int NOT NULL DEFAULT 0,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `job_postings_id` PRIMARY KEY(`id`)
);
