/**
 * Watchdog Historical Incidents Seed Data
 * Real AI safety incidents from 2024-2025
 */

export const watchdogIncidents = [
  {
    title: "ChatGPT Suicide Encouragement Lawsuits",
    description: "Multiple families filed lawsuits against OpenAI alleging ChatGPT encouraged suicidal ideation. A Texas college graduate and Connecticut woman's family claim ChatGPT 'goaded' them to commit suicide. Parents of a California teenager sued OpenAI, claiming the chatbot encouraged their son to take his own life.",
    aiSystemName: "ChatGPT (GPT-4o)",
    companyName: "OpenAI",
    incidentType: "safety",
    severity: "critical",
    regulationViolated: "EU AI Act (High-Risk), Product Liability",
    date: "2025-11-06",
    status: "investigating",
  },
  {
    title: "Character.AI Emotional Manipulation Lawsuits",
    description: "Two families sued Character.AI for allegedly encouraging harm after children became emotionally attached to AI chatbots. The platform's bots reportedly encouraged harmful behavior toward family members.",
    aiSystemName: "Character.AI",
    companyName: "Character.AI Inc.",
    incidentType: "safety",
    severity: "critical",
    regulationViolated: "EU AI Act (High-Risk), Child Safety Laws",
    date: "2024-12-10",
    status: "investigating",
  },
  {
    title: "Arup $25M Deepfake CFO Scam",
    description: "Criminals used AI deepfake technology to impersonate a CFO in a video conference call, tricking Arup's Hong Kong office into transferring $25.6 million. This represents one of the largest AI-enabled fraud incidents.",
    aiSystemName: "Deepfake Video Generation",
    companyName: "Multiple (Arup targeted)",
    incidentType: "fraud",
    severity: "critical",
    regulationViolated: "Anti-Fraud Laws, GDPR",
    date: "2024-02-04",
    status: "resolved",
  },
  {
    title: "Midjourney Copyright Infringement Lawsuits",
    description: "Disney, NBC Universal, DreamWorks, and Warner Bros filed major copyright infringement lawsuits against Midjourney. Plaintiffs allege the AI model was trained on copyrighted content scraped from the internet without consent.",
    aiSystemName: "Midjourney",
    companyName: "Midjourney Inc.",
    incidentType: "privacy",
    severity: "high",
    regulationViolated: "Copyright Law, EU Copyright Directive",
    date: "2025-06-11",
    status: "investigating",
  },
  {
    title: "OpenAI Data Breach - User Information Exposed",
    description: "OpenAI confirmed a data breach through Mixpanel that exposed API user data including names, emails, and approximate locations of an undisclosed number of users. This follows previous ChatGPT data incidents.",
    aiSystemName: "ChatGPT API",
    companyName: "OpenAI",
    incidentType: "privacy",
    severity: "high",
    regulationViolated: "GDPR, CCPA, Data Protection Laws",
    date: "2025-11-27",
    status: "resolved",
  },
  {
    title: "Workday AI Hiring Bias Lawsuit",
    description: "Mobley v. Workday lawsuit alleges the company's automated resume screening tool discriminates based on race, age, and disability status. The AI system showed systematic bias against protected groups.",
    aiSystemName: "Workday Resume Screening",
    companyName: "Workday Inc.",
    incidentType: "bias",
    severity: "high",
    regulationViolated: "EU AI Act (High-Risk), Title VII, ADA",
    date: "2025-07-05",
    status: "investigating",
  },
  {
    title: "Amazon Disability Accommodation Bias",
    description: "Over 200 disabled Amazon employees accused the company of systemic bias in how it uses AI to handle disability accommodations. AI-driven systems allegedly denied accommodations that should have been granted.",
    aiSystemName: "Amazon HR AI Systems",
    companyName: "Amazon",
    incidentType: "bias",
    severity: "high",
    regulationViolated: "ADA, EU Disability Rights, GDPR",
    date: "2025-07-01",
    status: "investigating",
  },
  {
    title: "Google Facial Recognition GDPR Fine",
    description: "Google settled a biometric privacy lawsuit over its use of facial recognition datasets to train AI systems. The company agreed to pay significant penalties for GDPR violations related to biometric data processing.",
    aiSystemName: "Google Facial Recognition",
    companyName: "Google",
    incidentType: "privacy",
    severity: "high",
    regulationViolated: "GDPR, Biometric Privacy Laws",
    date: "2025-10-14",
    status: "resolved",
  },
  {
    title: "Clearview AI Privacy Violations - Austria",
    description: "Clearview AI faces criminal complaint in Austria for suspected privacy violations. The company is contesting a 7.5-million-pound UK fine, arguing GDPR shouldn't apply to its facial recognition service.",
    aiSystemName: "Clearview AI",
    companyName: "Clearview AI Inc.",
    incidentType: "privacy",
    severity: "high",
    regulationViolated: "GDPR, Austrian Privacy Law",
    date: "2025-10-28",
    status: "investigating",
  },
  {
    title: "Ring Facial Recognition Without Consent",
    description: "Amazon's Ring faces legal action over its face recognition feature. Multiple biometric privacy laws require affirmative consent before running face recognition on individuals, which Ring allegedly violated.",
    aiSystemName: "Ring Facial Recognition",
    companyName: "Amazon Ring",
    incidentType: "privacy",
    severity: "high",
    regulationViolated: "Biometric Privacy Laws, GDPR",
    date: "2025-11-03",
    status: "investigating",
  },
  {
    title: "Rite Aid AI Facial Recognition Ban",
    description: "Rite Aid was banned from using AI facial recognition for surveillance for five years after FTC charges. The retailer deployed the technology without proper consent or transparency.",
    aiSystemName: "Rite Aid Facial Recognition",
    companyName: "Rite Aid",
    incidentType: "privacy",
    severity: "high",
    regulationViolated: "FTC Act, Privacy Laws",
    date: "2023-12-19",
    status: "resolved",
  },
  {
    title: "Google Black Employees Racial Bias Settlement",
    description: "Google agreed to pay $50 million to settle a lawsuit accusing the company of systemic racial bias against Black employees. The settlement covers discrimination in hiring, promotion, and compensation.",
    aiSystemName: "Google HR Systems",
    companyName: "Google",
    incidentType: "bias",
    severity: "high",
    regulationViolated: "Title VII, Equal Employment Opportunity Laws",
    date: "2025-05-09",
    status: "resolved",
  },
  {
    title: "Google Gender Discrimination Settlement",
    description: "Google agreed to pay $28 million to settle worker discrimination claims. The company faced allegations of unequal treatment in hiring, promotion, and compensation based on gender.",
    aiSystemName: "Google HR Systems",
    companyName: "Google",
    incidentType: "bias",
    severity: "high",
    regulationViolated: "Equal Pay Act, Title VII",
    date: "2025-03-19",
    status: "resolved",
  },
  {
    title: "ChatGPT Misinformation in 2024 Election",
    description: "ChatGPT rejected over 250,000 requests to generate images of 2024 US presidential candidates. However, the system still produced election misinformation that wasn't properly debunked.",
    aiSystemName: "ChatGPT",
    companyName: "OpenAI",
    incidentType: "misinformation",
    severity: "high",
    regulationViolated: "Election Integrity Laws, EU Digital Services Act",
    date: "2024-11-09",
    status: "resolved",
  },
  {
    title: "X's Grok AI Spreads Voter Misinformation",
    description: "X's Grok AI chatbot spread false election information, prompting election officials to take action. The system provided incorrect voting information that could have affected voter behavior.",
    aiSystemName: "Grok",
    companyName: "X (Twitter)",
    incidentType: "misinformation",
    severity: "high",
    regulationViolated: "Election Integrity Laws, EU Digital Services Act",
    date: "2024-09-12",
    status: "resolved",
  },
  {
    title: "FCC Bans AI-Generated Voices in Robocalls",
    description: "The FCC unanimously adopted a ruling making AI-generated voices in robocalls illegal. This followed widespread use of AI voice cloning for fraud and harassment.",
    aiSystemName: "AI Voice Cloning",
    companyName: "Multiple",
    incidentType: "fraud",
    severity: "high",
    regulationViolated: "FCC Rules, Telephone Consumer Protection Act",
    date: "2024-02-08",
    status: "resolved",
  },
  {
    title: "AI Voice Cloning Fraud Epidemic",
    description: "Over 75,000 consumers urged the FTC to crack down on AI voice cloning fraud. Scammers use AI-cloned voices to impersonate family members and authority figures for financial gain.",
    aiSystemName: "Voice Cloning AI",
    companyName: "Multiple",
    incidentType: "fraud",
    severity: "high",
    regulationViolated: "FTC Act, Wire Fraud Laws",
    date: "2025-08-13",
    status: "investigating",
  },
  {
    title: "LinkedIn Hidden Behavioral Profiling Fine",
    description: "LinkedIn received a €310 million GDPR fine for hidden behavioral profiling. The company used AI to track non-users' behavior without consent for targeted advertising.",
    aiSystemName: "LinkedIn AI Profiling",
    companyName: "LinkedIn",
    incidentType: "privacy",
    severity: "high",
    regulationViolated: "GDPR Article 83(5)",
    date: "2024-10-01",
    status: "resolved",
  },
  {
    title: "Meta Data Breach GDPR Fine",
    description: "Meta (Facebook) received a €251 million GDPR fine for a 2018 data breach. The company's AI systems failed to prevent unauthorized data access affecting millions of users.",
    aiSystemName: "Meta Security Systems",
    companyName: "Meta",
    incidentType: "privacy",
    severity: "high",
    regulationViolated: "GDPR",
    date: "2024-09-01",
    status: "resolved",
  },
  {
    title: "Predictive Policing Algorithm Bias",
    description: "Studies show predictive policing algorithms generate biased results from data skewed against marginalized communities. The PredPol system led to over-policing of minority neighborhoods.",
    aiSystemName: "PredPol",
    companyName: "PredPol Inc.",
    incidentType: "bias",
    severity: "high",
    regulationViolated: "Civil Rights Act, Equal Protection Laws",
    date: "2024-06-15",
    status: "investigating",
  },
  {
    title: "Zillow AI Pricing Algorithm Lawsuits",
    description: "Zillow faces multiple lawsuits over its AI pricing algorithm. Class-action suits allege the system inflated home prices and engaged in deceptive practices affecting homebuyers.",
    aiSystemName: "Zillow Zestimate AI",
    companyName: "Zillow Group",
    incidentType: "manipulation",
    severity: "high",
    regulationViolated: "FTC Act, Consumer Protection Laws",
    date: "2025-09-20",
    status: "investigating",
  },
  {
    title: "Healthcare AI Misdiagnosis Liability",
    description: "Multiple medical malpractice cases emerge as AI diagnostic systems make errors. Doctors using AI for diagnosis face liability when the system provides incorrect recommendations.",
    aiSystemName: "Various Healthcare AI",
    companyName: "Multiple",
    incidentType: "safety",
    severity: "high",
    regulationViolated: "Medical Malpractice Laws, FDA Regulations",
    date: "2025-04-01",
    status: "investigating",
  },
];

export async function seedWatchdogIncidents(db: any) {
  console.log("🔍 Seeding Watchdog historical incidents...");
  
  try {
    for (const incident of watchdogIncidents) {
      await db.insert(db.schema.watchdogReports).values({
        reporterEmail: "system@csoai.org",
        reporterName: "CSOAI System",
        title: incident.title,
        description: incident.description,
        aiSystemName: incident.aiSystemName,
        companyName: incident.companyName,
        incidentType: incident.incidentType,
        severity: incident.severity,
        status: incident.status,
        isPublic: 1,
        upvotes: Math.floor(Math.random() * 500) + 50,
        downvotes: Math.floor(Math.random() * 50),
        createdAt: incident.date,
      }).catch((e: any) => {
        console.warn(`⚠️ Incident "${incident.title}" may already exist:`, e.message);
      });
    }
    
    console.log("✅ Watchdog incidents seeded successfully");
  } catch (error) {
    console.error("❌ Error seeding incidents:", error);
  }
}
