/**
 * Referral Analytics PDF Generator
 * Generates professional PDF reports for referral analytics
 */

import PDFDocument from 'pdfkit';
import { ReferralAnalyticsService } from './referralAnalyticsService.js';

export class ReferralPdfGenerator {
  /**
   * Generate a PDF report for referral analytics
   */
  static async generateAnalyticsPDF(
    userId: number,
    dateRange: 'week' | 'month' | 'quarter' = 'month'
  ): Promise<Buffer> {
    return new Promise(async (resolve, reject) => {
      try {
        // Get analytics data
        const analytics = await ReferralAnalyticsService.getReferralAnalytics(userId, dateRange);
        const summary = await ReferralAnalyticsService.getReferralSummary(userId);

        // Create PDF document
        const doc = new PDFDocument({
          size: 'A4',
          margin: 40,
        });

        const chunks: Buffer[] = [];

        // Collect PDF data
        doc.on('data', (chunk: Buffer) => {
          chunks.push(chunk);
        });

        doc.on('end', () => {
          resolve(Buffer.concat(chunks));
        });

        doc.on('error', (err) => {
          reject(err);
        });

        // Title
        doc.fontSize(24).font('Helvetica-Bold').text('Referral Analytics Report', { align: 'center' });
        doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
        doc.fontSize(10).text(`Date Range: ${this.formatDateRange(dateRange)}`, { align: 'center' });
        doc.moveDown(1);

        // Summary Metrics Section
        doc.fontSize(14).font('Helvetica-Bold').text('Summary Metrics', { underline: true });
        doc.moveDown(0.5);

        // Create metrics table
        const metricsData = [
          ['Metric', 'Value'],
          ['Total Clicks', analytics.totalClicks.toString()],
          ['Total Conversions', analytics.totalConversions.toString()],
          ['Total Earnings', `$${analytics.totalEarnings.toFixed(2)}`],
          ['Conversion Rate', `${analytics.conversionRate.toFixed(2)}%`],
          ['Average Commission', `$${analytics.averageCommissionPerConversion.toFixed(2)}`],
          ['Active Referral Codes', summary.activeReferralCodes.toString()],
          ['Pending Earnings', `$${summary.pendingEarnings.toFixed(2)}`],
        ];

        this.drawTable(doc, metricsData, 50, 150, 500);
        doc.moveDown(2);

        // Top Referral Codes Section
        if (analytics.topReferralCodes.length > 0) {
          doc.fontSize(14).font('Helvetica-Bold').text('Top Referral Codes', { underline: true });
          doc.moveDown(0.5);

          const codesData = [
            ['Code', 'Clicks', 'Conversions', 'Earnings'],
            ...analytics.topReferralCodes.map((code) => [
              code.code,
              code.clicks.toString(),
              code.conversions.toString(),
              `$${code.earnings.toFixed(2)}`,
            ]),
          ];

          this.drawTable(doc, codesData, 50, doc.y, 500);
          doc.moveDown(2);
        }

        // Performance Insights Section
        doc.fontSize(14).font('Helvetica-Bold').text('Performance Insights', { underline: true });
        doc.moveDown(0.5);

        const bestCode = analytics.topReferralCodes[0];
        const avgClicksPerCode = summary.totalReferralCodes > 0 ? analytics.totalClicks / summary.totalReferralCodes : 0;
        const avgConversionsPerCode = summary.totalReferralCodes > 0 ? analytics.totalConversions / summary.totalReferralCodes : 0;
        const avgEarningsPerCode = summary.totalReferralCodes > 0 ? analytics.totalEarnings / summary.totalReferralCodes : 0;

        doc.fontSize(10).font('Helvetica');
        doc.text(`• Best performing code: ${bestCode?.code || 'N/A'}`);
        doc.text(`• Average clicks per code: ${avgClicksPerCode.toFixed(2)}`);
        doc.text(`• Average conversions per code: ${avgConversionsPerCode.toFixed(2)}`);
        doc.text(`• Average earnings per code: $${avgEarningsPerCode.toFixed(2)}`);
        doc.moveDown(1);

        // Footer
        doc.fontSize(8).font('Helvetica').fillColor('#999999').text('This is an automated report generated by CSOAI Referral Analytics System', {
          align: 'center',
        });
        doc.fillColor('black');

        // Finalize PDF
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Draw a table on the PDF document
   */
  private static drawTable(
    doc: any,
    data: string[][],
    x: number,
    y: number,
    width: number,
    options: { rowHeight?: number; fontSize?: number } = {}
  ) {
    const rowHeight = options.rowHeight || 20;
    const fontSize = options.fontSize || 9;
    const colWidth = width / data[0].length;

    let currentY = y;

    data.forEach((row, rowIndex) => {
      const isHeader = rowIndex === 0;

      // Draw row background
      if (isHeader) {
        doc.rect(x, currentY, width, rowHeight).fill('#f3f4f6');
      }

      // Draw cells
      row.forEach((cell, colIndex) => {
        const cellX = x + colIndex * colWidth;

        // Draw cell border
        doc.rect(cellX, currentY, colWidth, rowHeight).stroke();

        // Draw cell text
        doc.fontSize(fontSize)
          .font(isHeader ? 'Helvetica-Bold' : 'Helvetica')
          .text(cell, cellX + 5, currentY + 5, {
            width: colWidth - 10,
            height: rowHeight - 10,
            align: 'left',
          });
      });

      currentY += rowHeight;
    });
  }

  /**
   * Format date range for display
   */
  private static formatDateRange(dateRange: 'week' | 'month' | 'quarter'): string {
    const now = new Date();
    let startDate = new Date();

    if (dateRange === 'week') {
      startDate.setDate(now.getDate() - 7);
      return `Last 7 Days (${startDate.toLocaleDateString()} - ${now.toLocaleDateString()})`;
    } else if (dateRange === 'month') {
      startDate.setMonth(now.getMonth() - 1);
      return `Last 30 Days (${startDate.toLocaleDateString()} - ${now.toLocaleDateString()})`;
    } else if (dateRange === 'quarter') {
      startDate.setMonth(now.getMonth() - 3);
      return `Last 90 Days (${startDate.toLocaleDateString()} - ${now.toLocaleDateString()})`;
    }

    return 'Unknown';
  }
}
